Repository DeveloperAcademy-POSTECH/MC2-Team7-Larasy, pull requests merged in 2022-11, with the labels that each got.

#80 Fix # 74 기록 저장시 앱 종료 버그 수정
  Record/Views/DetailViews/RecordDetailView.swift
  Record/Views/WriteViews/SearchView.swift
  Record/Views/WriteViews/WriteView.swift
Labels: 🐛 bug

#81 [Feat] #75 검색 결과 초기화
  Record/Views/CDListView/CdListView.swift
  Record/Views/HomeView.swift
  Record/Views/WriteViews/SearchView.swift
Labels: 🌟 enhancement

#82 Version 1.0.1
  Record.xcodeproj/project.pbxproj
  Record/Views/CDListView/CdListView.swift
  Record/Views/DetailViews/RecordDetailView.swift
  Record/Views/HomeView.swift
  Record/Views/WriteViews/SearchView.swift
  Record/Views/WriteViews/WriteView.swift
Labels: Release
