Repository DeveloperAcademy-POSTECH/MC2-Team7-Larasy, pull requests merged in 2023-02, with the labels that each got.

#86 [Feat] 수정 후 리스트 업데이트 안 되는 문제 해결
  Record.xcodeproj/project.pbxproj
  Record/Views/Components/URLImage.swift
  Record/Views/WriteViews/SearchView.swift
Labels: 🐛 bug

#84 [Fix] #71 - 저장되는 이미지를 png에서 jpeg로 변경
  Record/Views/WriteViews/WriteView.swift
Labels: 🐛 bug

#88 [Feat] 패딩 값 수정
  Record/Views/HomeView.swift
Labels: 🖼 design

#89 Version 1.0.2
  Record.xcodeproj/project.pbxproj
  Record/Views/CDListView/SnapCarouselView.swift
  Record/Views/Components/URLImage.swift
  Record/Views/DetailViews/RecordDetailView.swift
  Record/Views/HomeView.swift
  Record/Views/WriteViews/SearchView.swift
  Record/Views/WriteViews/WriteView.swift
Labels: Release

#95 [Fix] #90 - 이미지 선택 후 애니메이션이 동작하지 않는 버그 수정
  Record/Views/DetailViews/PhotoModalView.swift
  Record/Views/DetailViews/RecordDetailView.swift
  Record/Views/DetailViews/StoryModalView.swift
  Record/Views/WriteViews/WritingModalView.swift
Labels: 🐛 bug

#96 [Feat] #92 - marquee textView 적용
  Record.xcodeproj/project.pbxproj
  Record/Extensions/Font+Extensions.swift
  Record/Views/CDListView/MarqueeTextView.swift
  Record/Views/CDListView/SnapCarouselView.swift
Labels: 🌟 enhancement

#97 [Feat] #39 - Carousel 수정
  Record.xcodeproj/project.pbxproj
  Record/Extensions/View+Extensions.swift
  Record/Views/CDListView/CDList.swift
  Record/Views/CDListView/CDListView.swift
  Record/Views/CDListView/CDPlayer.swift
  Record/Views/CDListView/Carousel.swift
  Record/Views/CDListView/CdListView.swift
  Record/Views/CDListView/EmptyCDListView.swift
  Record/Views/CDListView/MusicInformation.swift
  Record/Views/Components/FramePreferenceKey.swift
  Record/Views/HomeView.swift
Labels: 🌟 enhancement

#101 [Release] version 1.0.3
  Record.xcodeproj/project.pbxproj
  Record/Extensions/Font+Extensions.swift
  Record/Extensions/View+Extensions.swift
  Record/Views/CDListView/CDList.swift
  Record/Views/CDListView/CDListView.swift
  Record/Views/CDListView/CDPlayer.swift
  Record/Views/CDListView/Carousel.swift
  Record/Views/CDListView/CdListView.swift
  Record/Views/CDListView/EmptyCDListView.swift
  Record/Views/CDListView/MarqueeTextView.swift
  Record/Views/CDListView/MusicInformation.swift
  Record/Views/CDListView/SnapCarouselView.swift
  Record/Views/Components/FramePreferenceKey.swift
  Record/Views/DetailViews/PhotoModalView.swift
  Record/Views/DetailViews/RecordDetailView.swift
  Record/Views/DetailViews/StoryModalView.swift
  Record/Views/HomeView.swift
  Record/Views/WriteViews/WritingModalView.swift
Labels: Release
